export const GET_USER_AND_FRIENDS_REQUEST = 'GET_USER_AND_FRIENDS_REQUEST';
export const GET_USER_AND_FRIENDS_SUCCESS = 'GET_USER_AND_FRIENDS_SUCCESS';
export const GET_USER_AND_FRIENDS_FAIL = 'GET_USER_AND_FRIENDS_FAIL';

export const getUserAndFriends(steamID) {

}
